# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master  # Set this to your preferred branch trigger

pool:
  vmImage: 'windows-latest'  # Use a Windows agent for Windows Server

variables:
  buildConfiguration: 'Release'  # You can change this to 'Debug' if needed

steps:
- script: |
    dotnet restore
    dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/app
  displayName: 'Build and Publish .NET Core Web API'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Create ZIP Archive'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'dotnet-core-app-artifact'
    publishLocation: 'Container'
  displayName: 'Publish ZIP Artifact'