using SupervisorMobility.API.DataAccess.Entities.HRI_s_Entities;
using SupervisorMobility.API.Models.HRICyclesDtos;
using SupervisorMobility.API.Models.HRIHourmeterRevisionDto;
using SupervisorMobility.API.Models.HRIRevisionItemsDtos;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< enma_dev_06042026
using SupervisorMobility.API.Models.HRIWeeklyRevisions;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
using SupervisorMobility.API.Models.HRIDtos.HRImagesDto;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feat/imgls16

namespace SupervisorMobility.API.Models.HRIDtos
{
    public class CreateHRIDto
    {
        public int? HRILinesId { get; set; }
        public HRILines? Line { get; set; }
        public int? HRIItemId { get; set; }
        public HRIItem? NameOfItem { get; set; }
        public string? ControlNumber { get; set; }
        public int? HRIDockId { get; set; }
        public HRIDock? Dock { get; set; }
        public string? Department { get; set; }
        public List<CreateHRImageDto>? Images { get; set; }
        public List<CreateHRIRevisionItemDto>? ItemsRevised { get; set; }
        public List<CreateWeeklyRevisionDto>? WeeklyRevisions { get; set; }
        public List<CreateHRICyclesDto>? HriCycles { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreationDate { get; set; }
        public CreateHourMeterRevisionDto? HourmeterRevision { get; set; }
        public int? SupervisorUserId { get; set; }
        public int? SSVUserId { get; set; }
        public int? PlantId { get; set; }
        public int? AreaId { get; set; }

    }
}
