// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupervisorMobility.API.Context;

#nullable disable

namespace SupervisorMobility.API.Migrations
{
    [DbContext(typeof(SupervisorMobilityContext))]
    [Migration("20220803020758_AddSeedingForJobObservationConfig")]
    partial class AddSeedingForJobObservationConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistCategory", b =>
                {
                    b.Property<int>("ChecklistCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistCategoryId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ChecklistCategoryId");

                    b.ToTable("ChecklistCategories");

                    b.HasData(
                        new
                        {
                            ChecklistCategoryId = 1,
                            Code = "PO",
                            Description = "Preparación de la Observación",
                            IsActive = true,
                            Sequence = 1
                        },
                        new
                        {
                            ChecklistCategoryId = 2,
                            Code = "OPCE",
                            Description = "Observación para el cumplimiento del estándar - Observación de lejos",
                            IsActive = true,
                            Sequence = 2
                        },
                        new
                        {
                            ChecklistCategoryId = 3,
                            Code = "ATO",
                            Description = "Análisis de tiempo de operación",
                            IsActive = true,
                            Sequence = 3
                        },
                        new
                        {
                            ChecklistCategoryId = 4,
                            Code = "OCE",
                            Description = "Observación para cumplimiento del estándar - Observación de cerca",
                            IsActive = true,
                            Sequence = 4
                        },
                        new
                        {
                            ChecklistCategoryId = 5,
                            Code = "OMEFE",
                            Description = "Observación para mejora del estándar de acuerdo al filtro elegido",
                            IsActive = true,
                            Sequence = 5
                        },
                        new
                        {
                            ChecklistCategoryId = 6,
                            Code = "TOSF",
                            Description = "Trabajo de Observación  - Sumario / Finalización",
                            IsActive = true,
                            Sequence = 6
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"), 1L, 1);

                    b.Property<int?>("AnswerSetID")
                        .HasColumnType("int");

                    b.Property<int>("CategorySequence")
                        .HasColumnType("int");

                    b.Property<int>("ChecklistCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("ChecklistCategoryId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("ChecklistQuestions");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            CategorySequence = 1,
                            ChecklistCategoryId = 1,
                            Code = "PO:ECA",
                            Description = "Estandares completos y actualizados",
                            IsActive = true,
                            Prompt = "Los estándares estan completos y actualizados (HOE, Estado de referencia de 5S, etc. Icluyendo la pasada observación de operación  (S/N)",
                            QuestionTypeId = 6
                        },
                        new
                        {
                            QuestionID = 2,
                            CategorySequence = 2,
                            ChecklistCategoryId = 1,
                            Code = "PO:NIO",
                            Description = "Nivel ILU del operador",
                            IsActive = true,
                            Prompt = "¿Cuál es nivel de ILU del operador?  ¿Está el entrenamiento alineado con el Cuadro de requisitos de Operaicón ? (S/N)",
                            QuestionTypeId = 6
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationConfig", b =>
                {
                    b.Property<int>("JobObservationConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationConfigId"), 1L, 1);

                    b.Property<int>("ChecklistCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobObservationTypeId")
                        .HasColumnType("int");

                    b.HasKey("JobObservationConfigId");

                    b.HasIndex("ChecklistCategoryId");

                    b.HasIndex("JobObservationTypeId");

                    b.ToTable("JobObservationConfigs");

                    b.HasData(
                        new
                        {
                            JobObservationConfigId = 1,
                            ChecklistCategoryId = 1,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 2,
                            ChecklistCategoryId = 2,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 3,
                            ChecklistCategoryId = 3,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 4,
                            ChecklistCategoryId = 4,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 5,
                            ChecklistCategoryId = 5,
                            JobObservationTypeId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationType", b =>
                {
                    b.Property<int>("JobObservationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationTypeId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("JobObservationTypeId");

                    b.ToTable("JobObservationTypes");

                    b.HasData(
                        new
                        {
                            JobObservationTypeId = 1,
                            Code = "JC",
                            Description = "Observación de Operación Cíclica",
                            IsActive = true
                        },
                        new
                        {
                            JobObservationTypeId = 2,
                            Code = "JNC",
                            Description = "Observación de Operación No Cíclica",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionTypeId"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("QuestionTypeId");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            QuestionTypeId = 1,
                            Code = "TXT",
                            Description = "Free text",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 2,
                            Code = "MC",
                            Description = "Multiple Choice",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 3,
                            Code = "NMB",
                            Description = "Number",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 4,
                            Code = "Date",
                            Description = "Date",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 5,
                            Code = "TM",
                            Description = "Time",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 6,
                            Code = "TF",
                            Description = "Si/No",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistQuestion", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.ChecklistCategory", "ChecklistCategory")
                        .WithMany("ChecklistQuestions")
                        .HasForeignKey("ChecklistCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.Entities.QuestionType", "QuestionType")
                        .WithMany("ChecklistQuestions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistCategory");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationConfig", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.ChecklistCategory", "ChecklistCategoryDto")
                        .WithMany()
                        .HasForeignKey("ChecklistCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.Entities.JobObservationType", "JobObservationTypeDto")
                        .WithMany("JobObservations")
                        .HasForeignKey("JobObservationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistCategoryDto");

                    b.Navigation("JobObservationTypeDto");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistCategory", b =>
                {
                    b.Navigation("ChecklistQuestions");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationType", b =>
                {
                    b.Navigation("JobObservations");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.QuestionType", b =>
                {
                    b.Navigation("ChecklistQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
