// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupervisorMobility.API.Context;

#nullable disable

namespace SupervisorMobility.API.Migrations
{
    [DbContext(typeof(SupervisorMobilityContext))]
    [Migration("20230213232151_Merge")]
    partial class Merge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("AreaId");

                    b.HasIndex("PlantId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            Code = "T1",
                            Description = "Trim 1",
                            IsActive = true,
                            PlantId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Distribution", b =>
                {
                    b.Property<int>("DistributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("DistributionId");

                    b.HasIndex("AreaId");

                    b.ToTable("Distributions");

                    b.HasData(
                        new
                        {
                            DistributionId = 1,
                            AreaId = 1,
                            Code = "Dist1",
                            Description = "Distribution 1 Trim 1",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Code = "P71A",
                            Description = "Infiniti P71A",
                            IsActive = true
                        },
                        new
                        {
                            ProductId = 3,
                            Code = "X247",
                            Description = "Mercedes X247",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.ProductDistribution", b =>
                {
                    b.Property<int>("ProductDistributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDistributionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductDistributionId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDistributions");

                    b.HasData(
                        new
                        {
                            ProductDistributionId = 1,
                            Code = "Dist1",
                            Description = "Distribution from products",
                            IsActive = true,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.ProductOperation", b =>
                {
                    b.Property<int>("ProductOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductOperationId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ProductDistributionId")
                        .HasColumnType("int");

                    b.HasKey("ProductOperationId");

                    b.HasIndex("ProductDistributionId");

                    b.ToTable("ProductOperations");

                    b.HasData(
                        new
                        {
                            ProductOperationId = 1,
                            Code = "OP1",
                            Description = "Operation from products",
                            IsActive = true,
                            ProductDistributionId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.SupportDocumentType", b =>
                {
                    b.Property<int>("SupportDocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportDocumentTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("SupportDocumentTypeId");

                    b.ToTable("SupportDocumentTypes");

                    b.HasData(
                        new
                        {
                            SupportDocumentTypeId = 1,
                            Code = "GOS",
                            Description = "GOS",
                            IsActive = true
                        },
                        new
                        {
                            SupportDocumentTypeId = 2,
                            Code = "HOE",
                            Description = "HOE",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.AssyChart", b =>
                {
                    b.Property<int>("AssyChardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssyChardId"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("CCP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("Date");

                    b.Property<int?>("DistributionId")
                        .HasColumnType("int");

                    b.Property<string>("GOS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("Date");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("AssyChardId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DistributionId");

                    b.HasIndex("OperationId");

                    b.HasIndex("PlantId");

                    b.HasIndex("ProductId");

                    b.ToTable("AssyCharts");

                    b.HasData(
                        new
                        {
                            AssyChardId = 1,
                            AreaId = 1,
                            CCP = "string",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DistributionId = 1,
                            GOS = "string",
                            HOE = "string",
                            IsActive = true,
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlantId = 1,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistCategory", b =>
                {
                    b.Property<int>("ChecklistCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ChecklistCategoryId");

                    b.HasIndex(new[] { "Code" }, "ix_cc_cod")
                        .IsUnique();

                    b.ToTable("ChecklistCategories", t =>
                        {
                            t.HasCheckConstraint("ck_cc_seq", "[Sequence] > 0");
                        });

                    b.HasData(
                        new
                        {
                            ChecklistCategoryId = 1,
                            Code = "PO",
                            Description = "Preparación de la Observación",
                            IsActive = true,
                            Sequence = 1
                        },
                        new
                        {
                            ChecklistCategoryId = 2,
                            Code = "OPCE",
                            Description = "Observación para el cumplimiento del estándar - Observación de lejos",
                            IsActive = true,
                            Sequence = 2
                        },
                        new
                        {
                            ChecklistCategoryId = 3,
                            Code = "ATO",
                            Description = "Análisis de tiempo de operación",
                            IsActive = true,
                            Sequence = 3
                        },
                        new
                        {
                            ChecklistCategoryId = 4,
                            Code = "OCE",
                            Description = "Observación para cumplimiento del estándar - Observación de cerca",
                            IsActive = true,
                            Sequence = 4
                        },
                        new
                        {
                            ChecklistCategoryId = 5,
                            Code = "OMEFE",
                            Description = "Observación para mejora del estándar de acuerdo al filtro elegido",
                            IsActive = true,
                            Sequence = 5
                        },
                        new
                        {
                            ChecklistCategoryId = 6,
                            Code = "TOSF",
                            Description = "Trabajo de Observación  - Sumario / Finalización",
                            IsActive = true,
                            Sequence = 6
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int?>("AnswerSetID")
                        .HasColumnType("int");

                    b.Property<int>("CategorySequence")
                        .HasColumnType("int");

                    b.Property<int>("ChecklistCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("ChecklistCategoryId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex(new[] { "Code" }, "ix_cq_cod")
                        .IsUnique();

                    b.ToTable("ChecklistQuestions", t =>
                        {
                            t.HasCheckConstraint("ck_cq_seq", "[CategorySequence] > 0");
                        });

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            CategorySequence = 1,
                            ChecklistCategoryId = 1,
                            Code = "PO:ECA",
                            Description = "Estandares completos y actualizados",
                            IsActive = true,
                            Prompt = "Los estándares estan completos y actualizados (HOE, Estado de referencia de 5S, etc. Icluyendo la pasada observación de operación  (S/N)",
                            QuestionTypeId = 6
                        },
                        new
                        {
                            QuestionID = 2,
                            CategorySequence = 2,
                            ChecklistCategoryId = 1,
                            Code = "PO:NIO",
                            Description = "Nivel ILU del operador",
                            IsActive = true,
                            Prompt = "¿Cuál es nivel de ILU del operador?  ¿Está el entrenamiento alineado con el Cuadro de requisitos de Operaicón ? (S/N)",
                            QuestionTypeId = 6
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Code = "GA",
                            Description = "Grupo A",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = 2,
                            Code = "GB",
                            Description = "Grupo B",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservation", b =>
                {
                    b.Property<int>("JobObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationId"));

                    b.Property<string>("Anomaly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("CArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cicles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistributionId")
                        .HasColumnType("int");

                    b.Property<string>("IdentifiedActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Models")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorCommentary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Option")
                        .HasColumnType("int");

                    b.Property<string>("OthersArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("QArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SsvCommentary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SsvSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time1HOE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time2HOE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateStart")
                        .HasColumnType("datetime2");

                    b.HasKey("JobObservationId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DistributionId");

                    b.HasIndex("OperationId");

                    b.HasIndex("PlantId");

                    b.ToTable("JobObservations");

                    b.HasData(
                        new
                        {
                            JobObservationId = 1,
                            AreaId = 1,
                            CArea = "Lorem ipsum dolor sit amet C Area",
                            Cicles = "1 min|2 min|3 min|4 min| 5 min",
                            DArea = "Lorem ipsum dolor sit amet D Area",
                            DistributionId = 1,
                            IdentifiedActivity = "Actividad identificada",
                            IsActive = true,
                            Models = "P71A|X247|P71A|X247|P71A",
                            Observer = "Pedro",
                            OperationId = 1,
                            Operator = "Juan",
                            OperatorCommentary = "Operator Commentary",
                            OperatorSignature = "Juan",
                            Option = 1,
                            OthersArea = "Lorem ipsum dolor sit amet Others Area",
                            PlantId = 1,
                            QArea = "Lorem ipsum dolor sit amet Q Area",
                            SArea = "Lorem ipsum dolor sit amet S Area",
                            SsvCommentary = "Senior Supervisor Commentary",
                            SsvSignature = "Pedro",
                            Time1HOE = "10 min",
                            Time2HOE = "20 min",
                            dateEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationConfig", b =>
                {
                    b.Property<int>("JobObservationConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationConfigId"));

                    b.Property<int>("ChecklistCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobObservationTypeId")
                        .HasColumnType("int");

                    b.HasKey("JobObservationConfigId");

                    b.HasIndex("ChecklistCategoryId");

                    b.HasIndex("JobObservationTypeId");

                    b.ToTable("JobObservationConfigs");

                    b.HasData(
                        new
                        {
                            JobObservationConfigId = 1,
                            ChecklistCategoryId = 1,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 2,
                            ChecklistCategoryId = 2,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 3,
                            ChecklistCategoryId = 3,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 4,
                            ChecklistCategoryId = 4,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 5,
                            ChecklistCategoryId = 5,
                            JobObservationTypeId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationType", b =>
                {
                    b.Property<int>("JobObservationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("JobObservationTypeId");

                    b.ToTable("JobObservationTypes");

                    b.HasData(
                        new
                        {
                            JobObservationTypeId = 1,
                            Code = "JC",
                            Description = "Observación de Operación Cíclica",
                            IsActive = true
                        },
                        new
                        {
                            JobObservationTypeId = 2,
                            Code = "JNC",
                            Description = "Observación de Operación No Cíclica",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DistributionId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("OperationId");

                    b.HasIndex("DistributionId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            OperationId = 1,
                            Code = "OP1",
                            Description = "Operacion Trim 1",
                            DistributionId = 1,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Code = "T&C",
                            Description = "Trim and Chassis",
                            IsActive = true
                        },
                        new
                        {
                            PlantId = 2,
                            Code = "Paint",
                            Description = "Paint",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("QuestionTypeId");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            QuestionTypeId = 1,
                            Code = "TXT",
                            Description = "Free text",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 2,
                            Code = "MC",
                            Description = "Multiple Choice",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 3,
                            Code = "NMB",
                            Description = "Number",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 4,
                            Code = "Date",
                            Description = "Date",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 5,
                            Code = "TM",
                            Description = "Time",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 6,
                            Code = "TF",
                            Description = "Si/No",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Area", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.Plant", "Plant")
                        .WithMany("Areas")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Distribution", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Area", "Area")
                        .WithMany("Distributions")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.ProductDistribution", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Product", null)
                        .WithMany("ProductDistributions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.ProductOperation", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.ProductDistribution", "productDistribution")
                        .WithMany("ProductOperations")
                        .HasForeignKey("ProductDistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productDistribution");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.AssyChart", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Distribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionId");

                    b.HasOne("SupervisorMobility.API.Entities.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId");

                    b.HasOne("SupervisorMobility.API.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Area");

                    b.Navigation("Distribution");

                    b.Navigation("Operation");

                    b.Navigation("Plant");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistQuestion", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.ChecklistCategory", "ChecklistCategory")
                        .WithMany("ChecklistQuestions")
                        .HasForeignKey("ChecklistCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.Entities.QuestionType", "QuestionType")
                        .WithMany("ChecklistQuestions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistCategory");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservation", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Distribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionId");

                    b.HasOne("SupervisorMobility.API.Entities.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId");

                    b.HasOne("SupervisorMobility.API.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.Navigation("Area");

                    b.Navigation("Distribution");

                    b.Navigation("Operation");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationConfig", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.ChecklistCategory", "ChecklistCategoryDto")
                        .WithMany()
                        .HasForeignKey("ChecklistCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.Entities.JobObservationType", "JobObservationTypeDto")
                        .WithMany("JobObservationConfigs")
                        .HasForeignKey("JobObservationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistCategoryDto");

                    b.Navigation("JobObservationTypeDto");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Operation", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Distribution", "Distribution")
                        .WithMany("Operations")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribution");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Area", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Distribution", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("ProductDistributions");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.ProductDistribution", b =>
                {
                    b.Navigation("ProductOperations");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistCategory", b =>
                {
                    b.Navigation("ChecklistQuestions");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationType", b =>
                {
                    b.Navigation("JobObservationConfigs");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Plant", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.QuestionType", b =>
                {
                    b.Navigation("ChecklistQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
