// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupervisorMobility.API.Context;

#nullable disable

namespace SupervisorMobility.API.Migrations
{
    [DbContext(typeof(SupervisorMobilityContext))]
    partial class SupervisorMobilityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DistributionProduct", b =>
                {
                    b.Property<int>("DistributionsDistributionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("DistributionsDistributionId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("DistributionProduct");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("AreaId");

                    b.HasIndex("PlantId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            Code = "T1",
                            Description = "Trim 1",
                            IsActive = true,
                            PlantId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Distribution", b =>
                {
                    b.Property<int>("DistributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("DistributionId");

                    b.HasIndex("AreaId");

                    b.ToTable("Distributions");

                    b.HasData(
                        new
                        {
                            DistributionId = 1,
                            AreaId = 1,
                            Code = "Dist1",
                            Description = "Distribution 1 Trim 1",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.FileUpload", b =>
                {
                    b.Property<int>("FileUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileUploadId"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LupId")
                        .HasColumnType("int");

                    b.Property<string>("StorageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("Date");

                    b.HasKey("FileUploadId");

                    b.HasIndex("LupId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Guides", b =>
                {
                    b.Property<int>("GuideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuideId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileUploadId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuideId");

                    b.HasIndex("FileUploadId");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.JobObservationVersion", b =>
                {
                    b.Property<int>("JobObservationVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationVersionId"));

                    b.Property<string>("Anomaly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Cicles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinalized")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistributionId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("JobObservationId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MadeBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Models")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int");

                    b.Property<string>("OperatorCommentary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("OperatorSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Option")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("SsvCommentary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SsvSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Time1HOE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time2HOE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("resumeVersion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobObservationVersionId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DistributionId");

                    b.HasIndex("JobObservationId");

                    b.HasIndex("OperationId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PlantId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("JobObservationHistory");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MadeBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationID = 1,
                            EntryDate = new DateTime(2023, 4, 7, 17, 34, 57, 821, DateTimeKind.Local).AddTicks(371),
                            IsAccepted = true,
                            IsActive = true,
                            MadeBy = "Marco Aguayo",
                            NotificationText = "Example of notify",
                            NotificationType = "info",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Code = "P71A",
                            Description = "Infiniti P71A",
                            IsActive = true
                        },
                        new
                        {
                            ProductId = 3,
                            Code = "X247",
                            Description = "Mercedes X247",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.SupportDocumentType", b =>
                {
                    b.Property<int>("SupportDocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportDocumentTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("SupportDocumentTypeId");

                    b.ToTable("SupportDocumentTypes");

                    b.HasData(
                        new
                        {
                            SupportDocumentTypeId = 1,
                            Code = "GOS",
                            Description = "GOS",
                            IsActive = true
                        },
                        new
                        {
                            SupportDocumentTypeId = 2,
                            Code = "HOE",
                            Description = "HOE",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("DisabledDate")
                        .HasColumnType("Date");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOperator")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("Date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Payroll")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("AreaId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PlantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AreaId = 1,
                            CreatedDate = new DateTime(2023, 4, 7, 17, 34, 57, 821, DateTimeKind.Local).AddTicks(306),
                            GroupId = 1,
                            IsActive = true,
                            IsAdmin = false,
                            IsOperator = false,
                            IsSupervisor = true,
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pedro",
                            Payroll = 12345,
                            PlantId = 1
                        },
                        new
                        {
                            UserId = 2,
                            AreaId = 1,
                            CreatedDate = new DateTime(2023, 4, 7, 17, 34, 57, 821, DateTimeKind.Local).AddTicks(310),
                            GroupId = 1,
                            IsActive = true,
                            IsAdmin = false,
                            IsOperator = true,
                            IsSupervisor = false,
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marco",
                            Payroll = 239935,
                            PlantId = 1
                        },
                        new
                        {
                            UserId = 3,
                            AreaId = 1,
                            CreatedDate = new DateTime(2023, 4, 7, 17, 34, 57, 821, DateTimeKind.Local).AddTicks(315),
                            GroupId = 1,
                            IsActive = true,
                            IsAdmin = true,
                            IsOperator = true,
                            IsSupervisor = true,
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marco Aguayo",
                            Payroll = 906,
                            PlantId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.AssyChart", b =>
                {
                    b.Property<int>("AssyChardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssyChardId"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("CCP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("Date");

                    b.Property<int?>("DistributionId")
                        .HasColumnType("int");

                    b.Property<string>("GOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("Date");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("AssyChardId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DistributionId");

                    b.HasIndex("OperationId");

                    b.HasIndex("PlantId");

                    b.HasIndex("ProductId");

                    b.ToTable("AssyCharts");

                    b.HasData(
                        new
                        {
                            AssyChardId = 1,
                            AreaId = 1,
                            CCP = "01. PRESS/01. CCP",
                            CreationDate = new DateTime(2023, 2, 25, 12, 55, 58, 303, DateTimeKind.Local),
                            DistributionId = 1,
                            GOS = "01. PRESS/01. MANUFACTURA/01. X247",
                            HOE = "1§01. PRESS/5§01. CALIDAD",
                            IsActive = true,
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OperationId = 1,
                            PlantId = 1,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistCategory", b =>
                {
                    b.Property<int>("ChecklistCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("ChecklistCategoryId");

                    b.HasIndex(new[] { "Code" }, "ix_cc_cod")
                        .IsUnique();

                    b.ToTable("ChecklistCategories", t =>
                        {
                            t.HasCheckConstraint("ck_cc_seq", "[Sequence] > 0");
                        });

                    b.HasData(
                        new
                        {
                            ChecklistCategoryId = 1,
                            Code = "PO",
                            Description = "Preparación de la Observación",
                            IsActive = true,
                            Sequence = 1
                        },
                        new
                        {
                            ChecklistCategoryId = 2,
                            Code = "OPCE",
                            Description = "Observación para el cumplimiento del estándar - Observación de lejos",
                            IsActive = true,
                            Sequence = 2
                        },
                        new
                        {
                            ChecklistCategoryId = 3,
                            Code = "ATO",
                            Description = "Análisis de tiempo de operación",
                            IsActive = true,
                            Sequence = 3
                        },
                        new
                        {
                            ChecklistCategoryId = 4,
                            Code = "OCE",
                            Description = "Observación para cumplimiento del estándar - Observación de cerca",
                            IsActive = true,
                            Sequence = 4
                        },
                        new
                        {
                            ChecklistCategoryId = 5,
                            Code = "OMEFE",
                            Description = "Observación para mejora del estándar de acuerdo al filtro elegido",
                            IsActive = true,
                            Sequence = 5
                        },
                        new
                        {
                            ChecklistCategoryId = 6,
                            Code = "TOSF",
                            Description = "Trabajo de Observación  - Sumario / Finalización",
                            IsActive = true,
                            Sequence = 6
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int?>("AnswerSetID")
                        .HasColumnType("int");

                    b.Property<int>("CategorySequence")
                        .HasColumnType("int");

                    b.Property<int>("ChecklistCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("ChecklistCategoryId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex(new[] { "Code" }, "ix_cq_cod")
                        .IsUnique();

                    b.ToTable("ChecklistQuestions", t =>
                        {
                            t.HasCheckConstraint("ck_cq_seq", "[CategorySequence] > 0");
                        });

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            CategorySequence = 1,
                            ChecklistCategoryId = 1,
                            Code = "PO:ECA",
                            Description = "Estandares completos y actualizados",
                            IsActive = true,
                            Prompt = "Los estándares estan completos y actualizados (HOE, Estado de referencia de 5S, etc. Icluyendo la pasada observación de operación  (S/N)",
                            QuestionTypeId = 6
                        },
                        new
                        {
                            QuestionID = 2,
                            CategorySequence = 2,
                            ChecklistCategoryId = 1,
                            Code = "PO:NIO",
                            Description = "Nivel ILU del operador",
                            IsActive = true,
                            Prompt = "¿Cuál es nivel de ILU del operador?  ¿Está el entrenamiento alineado con el Cuadro de requisitos de Operaicón ? (S/N)",
                            QuestionTypeId = 6
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Glosary", b =>
                {
                    b.Property<int>("GlosaryWordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GlosaryWordId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GlosaryWordId");

                    b.ToTable("Glosary");

                    b.HasData(
                        new
                        {
                            GlosaryWordId = 1,
                            Description = "Safety Pillar",
                            IsActive = true,
                            Name = "S"
                        },
                        new
                        {
                            GlosaryWordId = 2,
                            Description = "Quality Pillar",
                            IsActive = true,
                            Name = "Q"
                        },
                        new
                        {
                            GlosaryWordId = 3,
                            Description = "Delivery Pillar",
                            IsActive = true,
                            Name = "D"
                        },
                        new
                        {
                            GlosaryWordId = 4,
                            Description = "Cost Pillar",
                            IsActive = true,
                            Name = "C"
                        },
                        new
                        {
                            GlosaryWordId = 5,
                            Description = "Other",
                            IsActive = true,
                            Name = "Other"
                        },
                        new
                        {
                            GlosaryWordId = 6,
                            Description = "Senior Supervisor",
                            IsActive = true,
                            Name = "SSV"
                        },
                        new
                        {
                            GlosaryWordId = 7,
                            Description = "Supervisor",
                            IsActive = true,
                            Name = "SV"
                        },
                        new
                        {
                            GlosaryWordId = 8,
                            Description = "Listado único de problemas",
                            IsActive = true,
                            Name = "Lup"
                        },
                        new
                        {
                            GlosaryWordId = 9,
                            Description = "Tiempo ciclo de la operación por modelo",
                            IsActive = true,
                            Name = "Tiempo ciclo"
                        },
                        new
                        {
                            GlosaryWordId = 10,
                            Description = "Tiempo ciclo de la operación por modelo",
                            IsActive = true,
                            Name = "Tiempo de la HOE"
                        },
                        new
                        {
                            GlosaryWordId = 11,
                            Description = "Seguimiento de anomalías",
                            IsActive = true,
                            Name = "Manejo de la anomalía"
                        },
                        new
                        {
                            GlosaryWordId = 12,
                            Description = "Observación de la operación eventual",
                            IsActive = true,
                            Name = "Eventual"
                        },
                        new
                        {
                            GlosaryWordId = 13,
                            Description = "Observación de la operación planeada",
                            IsActive = true,
                            Name = "Planeada"
                        },
                        new
                        {
                            GlosaryWordId = 14,
                            Description = "Listado de distribución-Operación por etapa y planta",
                            IsActive = true,
                            Name = "Assy Chart"
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Code = "GA",
                            Description = "Grupo A",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = 2,
                            Code = "GB",
                            Description = "Grupo B",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservation", b =>
                {
                    b.Property<int>("JobObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationId"));

                    b.Property<string>("Anomaly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Cicles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinalized")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistributionId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Models")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int");

                    b.Property<string>("OperatorCommentary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("OperatorSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Option")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("SsvCommentary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SsvSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Time1HOE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time2HOE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("JobObservationId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DistributionId");

                    b.HasIndex("OperationId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PlantId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("JobObservations");

                    b.HasData(
                        new
                        {
                            JobObservationId = 1,
                            AreaId = 1,
                            Cicles = "3000|2500|3000|4000|1500",
                            DateEnd = new DateTime(2023, 4, 7, 17, 34, 57, 820, DateTimeKind.Local).AddTicks(9757),
                            DateFinalized = new DateTime(2023, 4, 7, 17, 34, 57, 820, DateTimeKind.Local).AddTicks(9758),
                            DateStart = new DateTime(2023, 4, 7, 17, 34, 57, 820, DateTimeKind.Local).AddTicks(9745),
                            DistributionId = 1,
                            IsActive = true,
                            Models = "1|1|1|1|1",
                            OperationId = 1,
                            OperatorCommentary = "Operator Commentary",
                            OperatorId = 2,
                            OperatorSignature = "",
                            Option = 1,
                            PlantId = 1,
                            SsvCommentary = "Senior Supervisor Commentary",
                            SsvSignature = "",
                            Status = 1,
                            SupervisorId = 1,
                            Time1HOE = "10 min",
                            Time2HOE = "20 min",
                            Type = 2
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationConfig", b =>
                {
                    b.Property<int>("JobObservationConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationConfigId"));

                    b.Property<int>("ChecklistCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobObservationTypeId")
                        .HasColumnType("int");

                    b.HasKey("JobObservationConfigId");

                    b.HasIndex("ChecklistCategoryId");

                    b.HasIndex("JobObservationTypeId");

                    b.ToTable("JobObservationConfigs");

                    b.HasData(
                        new
                        {
                            JobObservationConfigId = 1,
                            ChecklistCategoryId = 1,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 2,
                            ChecklistCategoryId = 2,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 3,
                            ChecklistCategoryId = 3,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 4,
                            ChecklistCategoryId = 4,
                            JobObservationTypeId = 1
                        },
                        new
                        {
                            JobObservationConfigId = 5,
                            ChecklistCategoryId = 5,
                            JobObservationTypeId = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationType", b =>
                {
                    b.Property<int>("JobObservationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobObservationTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("JobObservationTypeId");

                    b.ToTable("JobObservationTypes");

                    b.HasData(
                        new
                        {
                            JobObservationTypeId = 1,
                            Code = "JC",
                            Description = "Observación de Operación Cíclica",
                            IsActive = true
                        },
                        new
                        {
                            JobObservationTypeId = 2,
                            Code = "JNC",
                            Description = "Observación de Operación No Cíclica",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Lup", b =>
                {
                    b.Property<int>("LupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LupId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("JobObservationId")
                        .HasColumnType("int");

                    b.Property<int?>("JobObservationVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oportunity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pillar")
                        .HasColumnType("int");

                    b.Property<string>("Q3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("LupId");

                    b.HasIndex("JobObservationId");

                    b.HasIndex("JobObservationVersionId");

                    b.ToTable("Lup");

                    b.HasData(
                        new
                        {
                            LupId = 1,
                            CreatedDate = new DateTime(2023, 4, 7, 17, 34, 57, 821, DateTimeKind.Local).AddTicks(335),
                            EndDate = new DateTime(2023, 4, 7, 17, 34, 57, 821, DateTimeKind.Local).AddTicks(335),
                            IsActive = true,
                            JobObservationId = 1,
                            Observer = "Pedro",
                            Oportunity = "Operator need a safety helmet",
                            Pillar = 1,
                            Q3 = "contramedida inmediata",
                            Q4 = "contramedida definitiva",
                            Status = 1
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DistributionId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("OperationId");

                    b.HasIndex("DistributionId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            OperationId = 1,
                            Code = "OP1",
                            Description = "Operacion Trim 1",
                            DistributionId = 1,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Code = "T&C",
                            Description = "Trim and Chassis",
                            IsActive = true
                        },
                        new
                        {
                            PlantId = 2,
                            Code = "Paint",
                            Description = "Paint",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.QuestionType", b =>
                {
                    b.Property<int>("QuestionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("QuestionTypeId");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            QuestionTypeId = 1,
                            Code = "TXT",
                            Description = "Free text",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 2,
                            Code = "MC",
                            Description = "Multiple Choice",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 3,
                            Code = "NMB",
                            Description = "Number",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 4,
                            Code = "Date",
                            Description = "Date",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 5,
                            Code = "TM",
                            Description = "Time",
                            IsActive = true
                        },
                        new
                        {
                            QuestionTypeId = 6,
                            Code = "TF",
                            Description = "Si/No",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DistributionProduct", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Distribution", null)
                        .WithMany()
                        .HasForeignKey("DistributionsDistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Area", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.Plant", "Plant")
                        .WithMany("Areas")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Distribution", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Area", "Area")
                        .WithMany("Distributions")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.FileUpload", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.Lup", null)
                        .WithMany("Evidences")
                        .HasForeignKey("LupId");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Guides", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.FileUpload", "FileUpload")
                        .WithMany()
                        .HasForeignKey("FileUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileUpload");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.JobObservationVersion", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Distribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionId");

                    b.HasOne("SupervisorMobility.API.Entities.JobObservation", null)
                        .WithMany("History")
                        .HasForeignKey("JobObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.Entities.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("SupervisorMobility.API.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Area");

                    b.Navigation("Distribution");

                    b.Navigation("Operation");

                    b.Navigation("Operator");

                    b.Navigation("Plant");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Notification", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.User", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("SupervisorMobility.API.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SupervisorMobility.API.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.Navigation("Area");

                    b.Navigation("Group");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.AssyChart", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Distribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionId");

                    b.HasOne("SupervisorMobility.API.Entities.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId");

                    b.HasOne("SupervisorMobility.API.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Area");

                    b.Navigation("Distribution");

                    b.Navigation("Operation");

                    b.Navigation("Plant");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistQuestion", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.ChecklistCategory", "ChecklistCategory")
                        .WithMany("ChecklistQuestions")
                        .HasForeignKey("ChecklistCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.Entities.QuestionType", "QuestionType")
                        .WithMany("ChecklistQuestions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistCategory");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservation", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Distribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionId");

                    b.HasOne("SupervisorMobility.API.Entities.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("SupervisorMobility.API.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId");

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Area");

                    b.Navigation("Distribution");

                    b.Navigation("Operation");

                    b.Navigation("Operator");

                    b.Navigation("Plant");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationConfig", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.ChecklistCategory", "ChecklistCategoryDto")
                        .WithMany()
                        .HasForeignKey("ChecklistCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.Entities.JobObservationType", "JobObservationTypeDto")
                        .WithMany("JobObservationConfigs")
                        .HasForeignKey("JobObservationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistCategoryDto");

                    b.Navigation("JobObservationTypeDto");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Lup", b =>
                {
                    b.HasOne("SupervisorMobility.API.Entities.JobObservation", null)
                        .WithMany("Lup")
                        .HasForeignKey("JobObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.JobObservationVersion", null)
                        .WithMany("Lup")
                        .HasForeignKey("JobObservationVersionId");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Operation", b =>
                {
                    b.HasOne("SupervisorMobility.API.DataAccess.Entities.Distribution", "Distribution")
                        .WithMany("Operations")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribution");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Area", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.Distribution", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("SupervisorMobility.API.DataAccess.Entities.JobObservationVersion", b =>
                {
                    b.Navigation("Lup");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.ChecklistCategory", b =>
                {
                    b.Navigation("ChecklistQuestions");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservation", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Lup");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.JobObservationType", b =>
                {
                    b.Navigation("JobObservationConfigs");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Lup", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.Plant", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("SupervisorMobility.API.Entities.QuestionType", b =>
                {
                    b.Navigation("ChecklistQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
