<Project Sdk="Microsoft.NET.Sdk.Web">

      <ItemGroup>
        <InternalsVisibleTo Include="Tests" />
      </ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.1.0</Version>
		<NoWarn>NU1701</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <Optimize>False</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <Optimize>false</Optimize>
	  <DebugType>full</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspose.Cells" Version="25.10.0" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CompareNETObjects" Version="4.83.0" />
		<PackageReference Include="CoreHtmlToImage" Version="1.0.6" />
		<PackageReference Include="CsvHelper" Version="33.0.1" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.4.1" />
		<PackageReference Include="DuoVia.FuzzyStrings" Version="2.1.0" />
		<PackageReference Include="EPPlus" Version="8.0.4" /> <!--Actualizar a version 8.4.0-->
		<PackageReference Include="FuzzySharp" Version="2.0.2" />
		<PackageReference Include="FuzzyString" Version="1.0.0" />
		<PackageReference Include="MailKit" Version="4.15.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.3" /> <!--Actualizar a version 10.0.3-->
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Graph.Core" Version="3.2.1" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.80.0" />
		<PackageReference Include="MimeKit" Version="4.15.1" />
		<PackageReference Include="ObjectCloner" Version="2.2.2" />
		<PackageReference Include="Quartz" Version="3.16.1" />
		<PackageReference Include="Quartz.Extensions.Hosting" Version="3.16.0" />
		<PackageReference Include="RabbitMQ.Client" Version="7.0.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
		<PackageReference Include="Slugify.Core" Version="5.0.0-prerelease.4" />
		<PackageReference Include="SpreadsheetLight" Version="3.5.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" /> 
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="downloads\CCP\" />
		<Folder Include="downloads\GOS\" />
		<Folder Include="downloads\HOE\" />
		<Folder Include="Migrations\" />
		<Folder Include="Documents\" />
		<Folder Include="Temp\" />
		<Folder Include="uploads\assycharts\" />
		<Folder Include="uploads\attendance\" />
		<Folder Include="uploads\evidence\" />
		<Folder Include="uploads\guides\" />
		<Folder Include="uploads\headcount\" />
		<Folder Include="uploads\massive\" />
		<Folder Include="uploads\SOSData\Videos\" />
		<Folder Include="uploads\SOSData\CommonDirection\" />
		<Folder Include="uploads\SOSData\Images\" />
		<Folder Include="uploads\thenEvidence\" />
		<Folder Include="uploads\previousEvidence\" />
		<Folder Include="uploads\operatorSignature\" />
		<Folder Include="uploads\users\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Models\HRICyclesDtos\CreateHRICyclesDto.cs" />
	</ItemGroup>

	<Target Name="PublishFrontend" AfterTargets="ComputeFilesToPublish">
		<ItemGroup>
			<DistFiles Include="Documents\**" />
			<ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
				<RelativePath>%(DistFiles.Identity)</RelativePath>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
				<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>
	<Target Name="LogDirectoryOnPublish" BeforeTargets="Publish">
		<RemoveDir Condition="Exists('$(PublishUrl)')" Directories="$(PublishUrl)" />
		<MakeDir Directories="$(PublishUrl)\uploads\assycharts\" />
		<MakeDir Directories="$(PublishUrl)\uploads\attendance\" />
		<MakeDir Directories="$(PublishUrl)\uploads\evidence\" />
		<MakeDir Directories="$(PublishUrl)\uploads\guides\" />
		<MakeDir Directories="$(PublishUrl)\uploads\headcount\" />
		<MakeDir Directories="$(PublishUrl)\uploads\massive\" />
		<MakeDir Directories="$(PublishUrl)\uploads\thenEvidence\" />
		<MakeDir Directories="$(PublishUrl)\uploads\previousEvidence\" />
		<MakeDir Directories="$(PublishUrl)\uploads\operatorSignature\" />
		<MakeDir Directories="$(PublishUrl)\uploads\users\" />
		<MakeDir Directories="$(PublishUrl)\logs\" />
	</Target>

</Project>